name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup Python 3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # 3️⃣ Install system dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-venv

      # 4️⃣ Create virtual environment and install Buildozer
      - name: Setup Python virtualenv
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install cython
          pip install git+https://github.com/kivy/buildozer.git@master

      # 5️⃣ Build APK
      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer android debug

      # 6️⃣ Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MagmaApp-APK
          path: bin/*.apk
